---
title: "风先生"
author: "Angela Liu"
date: "March 17, 2015"
output: html_document
---

风先生：短距离配送持久战
2015年3月10日新闻报道
最后一公里配送一直是电商O2O的痛点。创业平台风先生基于LBS定位和大数据，建构起标准化配送流程，为本地生活O2O电商提供短距离配送服务，试图解决这一行业痛点。

在风先生CEO郑飞科看来，本地生活化O2O电商是未来的趋势，顺势而为，切入垂直细分O2O配送领域，可以避开与巨头竞争，建立差异化优势。而短距离快速配送恰是市场空白。不少O2O电商对有时效性要求的配送束手无策，自建物流成本高、管理难度大、配送能力有限，不及时送达容易影响客户体验。风先生切入配送市场，着力于短距离配送，总部接收商家订单后进行统一分配，并推送给配送员。配送员通过手机App接收订单，完成配送服务。2014年4月上线的风先生已经获得近千万美元A轮融资。

专攻短距离配送

风先生的创始人郑飞科是85后，曾加入胡莱三国早期创业团队，之后历任人人网产品经理和机锋网高级产品经理。2011年，郑飞科从北京回到杭州创立格子箱网络，开发设计了格子箱、配件盒子、海贼迷、极客咖啡、海贼天气等多款应用。2013年，郑飞科创办基于物品分享的社交化电商遭遇瓶颈，促使他开始思考创业的方向。

郑飞科告诉《天下网商》记者，任何业务模式都可以归为信息流或物理流，电商本质上也是这样。1.0时代的电商主攻信息流，譬如淘点点等以商家入驻模式为主的信息集合平台、社交化电商等。2.0时代的电商则是互联网和生活化的深度结合，电商、互联网的概念可能会逐步弱化，互联网更多作为一种工具和思考方式而存在，专注细分领域的垂直类生活化O2O电商在做信息流之余也侧重物理流，强调与线下传统行业的深度融合甚至是重构，从而树立起竞争壁垒。

创业的关键在于顺势而为。在这个大逻辑下，郑飞科打算从生活化O2O创业项目入手，切入垂直细分领域。他分析，目前很多餐饮类商家通过自建物流的形式进行外卖配送，扩展销售渠道，但对配送员的管理培训以及配送流程的制定是非标准化的，再加上外卖本身客单价不高，而最后一公里配送的人力及管理成本较高，导致商家的盈利能力变弱。因此，将配送人员集中起来进行统一培训，并制定标准化的配送流程，提高配送效率，为商户提供短距离快速配送服务，是郑飞科创立风先生的基本思路。

郑飞科介绍，风先生这种模式国内此前没有出现过，但是在美国纽约、洛杉矶等地已经有类似的模式实现了盈利。

事实上，从这种模式中受益最多的可能还不是外卖单量较大的餐饮商家，而是个人手工艺者。“现在，淘宝上有不少专注生鲜、烘焙的手工达人，限量制作沙拉、特色饼干等进行销售，在家里就可完成，免去了租金等实体店成本，但配送是一大难题。如果配送业务能够实现高性价比的外包，就像甲方将营销活动外包给广告公司一样，可以解放手工艺者，使他们更专注于产品本身，节省时间和精力。”郑飞科表示。

在创业初期，郑飞科曾尝试过“外卖平台加短距离配送”的模式，入驻平台的商家可以享受风先生的物流服务，但后来发现，做大做全未必合适，专攻小而精的外包配送服务反而能找到突破口。目前，风先生只接B端商户的批量订单，不与C端客户合作，一方面保证订单量，另一方面也可以通过集中为商户服务提高配送效率，降低配送成本。

调整模式

去年8月份，风先生对模式进行了调整，并于12月开始大规模扩张，在一个月内启动近十个城市，目前已经覆盖北京、上海、广州、深圳、苏州、南京、天津、长沙、杭州等一、二线城市的主城区。

早先，风先生的订单分配模式与打车软件很像，总部的工作人员会对订单进行实时地理定位，根据配送任务的难易程度和地点的远近，将订单有选择性地推送给几位“风先生”。“风先生”根据自身情况灵活决定是否接单，决定接单的几位“风先生”可以抢单。“风先生”的薪酬采取底薪加绩效的形式，每月必须完成规定的订单数，超出部分可以拿提成；如果连续几个月没有完成最低配送量，则会取消合作。

不过，郑飞科后来发现，抢单的形式并不利于资源的合理配置。由于商家要求配送的订单总量较大，但不少“风先生”只求达到最低配送量，不愿意接更多订单。同时，自主决定是否接单及抢单的模式会让部分“风先生”只愿意接单量较大、配送简单的商户的订单，最终导致小部分商户的订单无人配送。因此，郑飞科决定所有订单均由总部统一调配，“风先生”必须服从安排。“外卖配送与打车不同，一旦与商家合作，必须在规定时间内高效完成配送任务，保证服务的持续性和稳定性。而顾客使用打车软件没有及时叫到车，是在顾客接受范围内的。”

模式调整后，风先生总部参考传统物流的分配方式，基本以点对点服务为主，遵循就近原则，在同一方向进行分流配送。一家商户通常由一位配送员定点服务，如果该商家订单量较少，则会给配送员安排其他就近商家的订单。由于外卖的配送量每天都有变化，“风先生”服务的商户每天都可能调整，总部会在时间、空间、人力三者间做机动分配，保证每位“风先生”的时间得到充分利用。总部通常根据每个城市各个行政区块订单量的多少部署相应数量的配送员。

目前风先生主要通过与淘点点等外卖平台合作，开发商户资源。风先生每配送一单，商户都需要支出一笔配送费，商户提前在支付宝充值，直接按照单量扣钱。融到资后的风先生对商家进行补贴，以1元1单的促销活动推广配送服务，聚拢更多商户。外卖平台也会根据后台数据，给风先生推荐商户。

一般而言，以商家为中心的3～5公里范围风先生都可配送，通常半小时内可以送到，既可以是快餐，也可以是高端法式餐饮。

风先生创始人郑飞科创始人郑飞科

风先生”的标准化

“风先生”均为全职，通过App注册，且需要上传本人照片和身份证、健康证照片，并录入真实姓名、身份证号及居住地址。每位“风先生”只有一次上岗机会，一旦由于个人原因出现较严重的配送失误或商家投诉就会下岗，没有第二次加入的机会。

风先生还通过建立弹性配送体制规避配送过程中的风险，如果一位配送员在配送时出现问题，另一位配送员会接到该订单的信息，继续完成配送。未来风先生会尝试对顾客进行订单配送状态的实时提醒，配送人员一旦接到包裹，就会向顾客同步推送提醒短信。

目前，“风先生”平均每人每天能配送60～80单，工作时间为10:00～20:00，主要客户群是小区的住户、写字楼的白领、学校的学生等。每位“风先生”均配有总部提供的定制配送箱，可以进行物理保温，冬天会放置加热垫。如果出现外卖掉落等问题导致返工，风先生会向商户道歉并承担损失。

风先生也在局部尝试为商户提供专门研发的餐盒，更大程度上保证食物的温度和质感，但尚未大规模推广。“这是出于完善客户体验的考虑，餐盒的成本较高，可能会针对部分高端餐饮店集中推送。”郑飞科说。

总部通过核心IT系统，实时了解配送员所处的位置、订单配送情况等，从而建立起对配送员的动态监控体系，并通过设置订单地理位置、配送员当前忙不忙、订单类型、配送员目前所在地等多种变量的优先级，以综合性的算法分配订单。订单由商家先发给总部IT系统，再由系统同步给配送员。

风先生在前期会对配送员进行统一培训，内容包括如何使用App软件接收订单、如何验小票验货、如何组装产品、送达顾客的标准术语、怎么注意交通安全等，并在后期定期进行远程培训，将商家和顾客的反馈意见实时传递给配送员，使其优化改进配送服务。风先生还建立了订单回访机制，定期对每位“风先生”送出的订单进行跟踪调查，对服务不达标的“风先生”给予相应处罚，并强化培训提高其配送能力。

随着风先生在全国布局速度的加快，今后总部系统可能需要调度几万人，这也更增加了培训上的难度。郑飞科正在尝试工厂化的复制模式，建构线上培训体系，复制“风先生”。“风先生”只需要按照手机指示执行步骤，就可以在不同场景的应对教程配合下，完成整体配送流程的学习。

目前，风先生已与近千名配送员建立起合作关系。等模式成熟后，风先生可能会将配送品类从需求量较大的外卖，进一步拓展到鲜花、水果、蛋糕、超市类用品等。郑飞科称，这与行业发展形势相关，淘宝的快速崛起带动了圆通、顺丰等传统物流企业的发展，淘点点等外卖平台的扩张同样也会促成短距离超速配送行业的探索和落地。
“商家将配送业务外包，可以增加日单量，减少人力和管理成本。配送服务商则可以利用互联网手段实现各类商家的集约化，摊薄成本，提高盈利能力。”郑飞科认为。

团队的打造

一年不到，风先生总部团队已经从一开始的20多人发展到现在的近百人，且还在进一步扩张中。郑飞科称，公司的DNA是互联网和传统物流的融合，虽然成长时间只有大半年，但业务和团队增长都是10倍以上数量级的变化，在这个快速变化的过程中，如何使人才价值与公司发展相匹配，是个需要考虑的问题。”

针对物流团队与互联网团队，郑飞科采取了不同的管理方式。传统物流团队分为三至四个层级，采用军事化管理，强调明确的目标传达和严格的命令执行；而针对互联网团队的管理则趋于扁平化，比较松散灵活。军事化并不意味着刻板和强迫，而是准确和严谨。传统物流团队主要负责短距离配送业务的落地，核心是流程轻、执行快，一旦任务没有传达清晰，就会产生连锁反应，大大降低客户体验。互联网团队正好相反，管得太紧容易扼杀创造性。

郑飞科坦言，配送行业本身很难赚钱，只有依靠极高的管理效率和人员利用率，将利润逼出来。风先生现在暂时不考虑盈利问题，而是致力于将模式打通，使业务稳定化、标准化，并在全国推开。

风先生刚刚谈下了一个新的办公场地，郑飞科打算将一楼变成一家沙拉餐厅，并利用风先生的配送服务做沙拉的外卖。这样做一方面是为员工提供福利，另一方面也可以了解到商家端在使用风先生时的直观体验，进一步优化和改进服务。

发表回复
风先生：主打餐饮O2O领域的最后一公里配送外包服务平台
2015年1月4日新闻报道
2014年餐饮O2O领域的厮杀继续越演越烈，淘点点用电商式的烧钱手法来收买用户；美团进军外卖，获得了7亿美金的融资；饿了么背靠大众点评拿到8000万美元D轮投资，预示着O2O餐饮平台成为团购大战后中国互联网的新一轮平台战争。今天猎云网给大家介绍的“风先生”就是一个基于LBS为这些O2O电商提供短距离餐饮配送服务的平台，目前，已经在全国二十多个城市试运营。

风先生是杭州格子箱网络有限公司旗下产品，创始人兼CEO郑飞科曾任职人人网产品经理、机锋网高级产品经理。风先生的核心管理团队成员既有来自网易、阿里巴巴、百度等互联网公司，也有来自顺丰、亚马逊、德邦等物流企业的管理人才。

风先生于2014年4月正式上线。“刚开始五月份的时候也想过做点餐平台，尝试了一段时间就发现点餐平台+配送的模式太重了，后来就专注于做配送了。”郑飞科告诉猎云网，创业初期他也尝试着做大、做全，但他逐渐意识到盘子铺太大未必是好事，干脆直接专注于做配送外包。

风先生会对城市的商圈进行划分，每个商圈内有一到两支配送队伍，商户有配送需求时直接在App平台上呼叫商圈内的配送员。“风先生只接商家的订单，暂时不接C端用户订单，这样一来既保证了订单量，也避免的C端用户的投诉。不涉及到C端，不向C端用户收取任何费用，只收取商家的配送费。”郑飞科向猎云网透露。

餐饮O2O配送有别于传统的快递公司，解决的是最后一公里的问题，时效性要求极强。“配送员全部都统一培训，且有严格的考核，不通过的无法上路配送”。风先生的配送员都是全职，对于配送员每个人每个月有最低配送订单量，如果达不到就没有底薪。

此外，商家申请入驻风先生平台时，后台人员审核时会做调查，在和配送部门以及市场确认过之后才会通过。商家提前在风先生平台上用支付宝充值，然后按照单量扣钱，收取的配送费都是提前和商家谈好的。只要合作之后，以这个商家为中心点的3—5公里都可以配送，基本在半小时内会送到消费者手中。配送的范围既涵盖高端的法式餐点，也包括黄焖鸡米饭等快餐。

风先生 内图 2_副本

郑飞科在接受猎云网采访时透露，风先生和商家的费用一般都是在平台结算，消费者通过淘点点、美团外卖等平台点餐，都是已经在平台上付了钱的。“如果是商家的电话订单，我们会送到货之后把收到的钱月结给商家，不过目前电话订单还是比较少。”

郑飞科告诉猎云网，他们在杭州的配送员个人配送的单量在成熟的商圈，平均每人能送60—80单。“商家这块的增长主要有两部分，一部分是我们市场的人去地推开发出来，另一部分是商户自己找上门来要求入驻，他们都有圈子，商户也会帮忙宣传。”郑飞科向猎云网透露。风先生的配送人员上班时间是上午10:00到20:00，目标用户是写字楼的白领和部分小区。

从趋势上来看，最后一公里这个概念必须有一个成型的行业来解决。“现在大家都在烧钱搞O2O，烧钱抢流量，我们的服务是比较偏后端的服务。”相比于餐饮店来说，自建配送队伍太重了，需要投入很多的钱和精力，人员管理也麻烦。因为配送途中出问题导致返工等，风先生会承担商户的损失，会和商户解释道歉。同时，风先生也有专门的工业设计师研发餐盒，定制配送箱，进行物理保温，冬天会放加热垫。

据了解，风先生并不是目前唯一一家做配送的公司，像点我吧点餐平台等也有自建的配送队伍。同样的领域，谁能最快找到适合的模式占领市场，就要看它的产品和运营，不过不容置疑的是未来外卖势必将朝着扁平化，自主化，垂直化发展。随着阿里、美团、百度相继加入到外卖O2O行业，独立发展的外卖O2O平台面临的竞争越来越大。

目前，风先生已完成A轮融资，具体金额及投资方不方便披露，猎云网会持续关注。

文章来源/猎云网

发表回复
风先生：要做好餐饮O2O，是时候开始注意配送服务了！
2014年12月30日新闻报道
无论现在点餐平台的格局如何，都在拼命地砸钱抢流量抢商户。随着几大点餐平台到店服务数据的下滑，更有公司全面撤退到店服务，餐饮O2O的重心似乎正在往外卖倾斜。

餐饮业作为传统意义上的服务业，在体验上有一点至关重要，就是服务。与品牌契合的服务，无论是到店消费还是外卖配送，都属于用户体验的重要部分。

按照原先方式，一旦有外卖订单，商户会让店内的服务员或者配送员送外卖。如果餐饮行业还未O2O，如果外卖还是原先的外卖，这一切都不是问题。但在巨大线上流量入侵的餐饮业，商户为了利用好“懒人经济”，必须要为外卖做好配送力量的准备。

虽然目前的形势还不明朗，但如果想要做好餐饮O2O，就必须要考虑好配送这个头疼的问题。本文将通过举业内较为成熟的例子，尽量证明配送在餐饮O2O中的重要性。

商户自主配送

商家自主解决外卖的配送，这种形式分为两种情况：服务员送外卖和自建配送队伍。

服务员送外卖：在高峰期动用服务员送外卖，让商户非常头痛。一来饭点期间店内人流量大，原本的服务员都不够用;二来外卖订单如果服务不好，导致顾客直接流失。

缺点：配送人员极度匮乏，面对餐饮O2O的浪潮，很难确保外卖订单都有人送。况且在评分体系下，一旦配送不及时，差评立即能被其他的顾客看到。

自建配送队伍：一般是大商户或品牌商户采用的方法，为了创造良好的服务体验，建立自己的外卖配送队伍，在餐饮O2O的大环境下，用大量的人力、资金投入来确保配送。如肯德基、必胜客。

缺点：自建配送队伍，出了初期大量的资金投入，后期的管理运营也成为一个很大的问题。尤其在快速发展的情况下，一直庞大的人力队伍，对商户来说很容易成为一大负担。

第三方配送服务

随着餐饮O2O的发展，第三方配送服务成为衍生行业，在重度垂直领域开辟了新的模式。作为第三方的服务商，想要获取客户(商户)信任，就必须保证能实际解决问题。

保证配送人力：第三方配送公司首先需要解决的就是人力问题，在短时间内(订单高峰期)聚集一大批配送人员帮商户解决配送问题，在最短的时间内，把外卖送到顾客手中。

保证配送质量：在配送时，配送人员直接代表商户，所以在确保人力充足的情况下，确保配送的质量成为第二步。据了解，风先生是一家餐饮O2O第三方配送公司，每一位配送员在上路配送前，都会对其进行系统的培训，并且由经验丰富的配送员带一段时间。

提升配送服务：在重服务的餐饮业，外卖的服务质量同样也是商户重视的一块。打个比方，一个衣着整洁的配送员，礼貌又亲和，还会和顾客开开玩笑，外卖送到之后也没有洒出来，这样顾客收到外卖，对商户的印象会大大加分。反之，如果一个外卖配送员衣着邋遢，满口脏话，送到的外卖随意乱放，顾客对这个商户的印象绝对会降到冰点。

在第三方配送的市场，像风先生这样的公司越来越多，模式几乎差不多，外卖众包，但是服务质量参差不齐，相信必然会有新一轮的行业洗牌，最终留下来的，才是最好的。

平台搭建配送队伍

对于流量最关键的点餐平台来说，搭建配送队伍，能给平台上的商户解决配送问题，希望更好地服务商户。

对于商户来说，当然是极好的，又解决了线上流量，又没有配送问题。但这一形式遇到一个明显的问题：不是此平台上的订单由谁配送?

对于平台而言，配送队伍属于服务，相对于流量这一核心要素，配送的优先级要低于能产生订单的流量。一般商户在平台上产生的流量，平台可以帮其配送，但如果是在其他平台上产生的订单，则无法帮商户配送，也是平台间相互竞争的一个结果。

餐饮O2O，如果没有配送，完成最后一步，那对于餐饮企业来说是致命的。所有在餐饮O2O浪潮中的企业，是时候注意起配送问题了。

文章来源/联商网