---
title: "muru-d"
author: "HarryZhu"
date: "March 14, 2015"
output: html_document
---
## 关于澳洲电信公司Telstra 旗下孵化器muru-D简介


muru-D是澳洲电信公司Telstra旗下的创业孵化器，我们的主要任务是支持和帮助澳洲地区最好的高科技数字创新公司。团队加入孵化后，muru-D将提供种子基金$ 40，000（来换取6 ％的股权）、6个月的协作办公空间、专业咨询师辅导、获取其他商业资源的途径，以及澳洲电信公司Telstra的关系网。 muru-D是由澳大利亚通讯部长Malcolm Turnbull在2013年10月推出的。



## muru-D二期孵化创业公司简介

muru-D第二期目前有11个创业团队。他们来自澳大利亚各地，是从180多个申请者中选拔而出的名列前茅的澳大利亚高科技创业公司。

1. [CrowdSourceHire](http://www.crowdsourcehire.com/) – 通过来自科技领域的专家小组对技术人员进行严谨技术评估的网络平台。 它能够帮助你聘用到最合适的科技类行业候选人。

2. [Disrupt](http://www.disruptsurfing.com/) – 通过采用3D建模打印技术来制作个性化冲浪板与其他体育用品网上销售平台。
3. [Fanfuel](http://www.fanfuel.co/) – 连接运动员和体育赞助商的在线平台。它使品牌公司能够轻松搜索运动员，获得安全有保障的赞助合同，并测量它们的投资回报率；同时它也帮助运动员了解他们自身的市场潜力。
4. [Freight Exchange](http://www.freightexchange.com.au/) – 帮助长途货运公司与客户建立良好连接的网络平台。它使得货运公司能够更高效的利用其产能，减少运输路途的空载量。
5. [Funetics](http://www.learningfunetics.com/) － Funetics是一个学习英文的语音技术平台。它帮助世界各地的用户掌握正确的英语发音和提高用户对英文的理解力。
6. [Instrument Works](http://www.instrument-works.com/) – 使实验室、田地以及工厂收集数据程序简易化，并通过由智能手机控制的和互联网链接的传感器设备来提供可靠和准确的信息。
7. [SoccerBrain](http://soccerbra.in/) – 帮助足球俱乐部来管理球员的训练、培训和发展的网上平台。
8. [Tripalocal](http://www.tripalocal.com/) – 在线平台连接旅行者和当地人，使旅行者有机会享受到正宗的当地体验－它提供像Airbnb一样的纯粹地方体验。
9. [Vclass](http://www.vclass.com.au/) - 有史以来第一个混合模式的教育平台。它通过结合互联网， VoIP和传统的纸笔教育模式，来创造一个全新的网上面对面教学体验。
10. [Wattblock](http://www.wattblock.com.au/) – 为住宅和商业用途的建筑提供快速的，个性化的，网络化的节能减排路线图，从而改善需要现场能源审计人员或安装硬件设备的高成本现状。
11. [You Chews](http://www.youchews.com/) – 为会议和活动提供美味的在线餐饮平台。

## 澳洲电信公司Telstra旗下孵化器 muru-D 和中国

从历史上看，澳大利亚的“高科技”创新企业之前几乎把发展重点完全放在美国市场上。然而，这已经随着中国的崛起开始转变了。Testra muru-D将通过以下方式推动中国这个新的市场焦点，引导孵化团队在2015年前半年关注这一新的趋势：

* 有意识地思考中国市场战略

* 寻求澳洲境内中国投资人的帮助，包括投资和咨询

* 花大量的时间在中国发展客户，寻求投资

muru-D也将通过此活动寻求和吸引一些最热门的中国高科技创业公司来到澳大利亚进行孵化。 本次活动将是整个蓝图的起始点。

